from aiogram.fsm.state import State, StatesGroup


class AdminStates(StatesGroup):
    add_admin = State()
    remove_admin = State()
    add_channel_id = State()
    add_channel_title = State()
    add_channel_button = State()
    remove_channel = State()
    set_backup_channel = State()
    edit_welcome = State()
    edit_auto_reply = State()
    edit_ban = State()
    edit_force_join = State()
    edit_admin_msg = State()
    edit_inactive_link = State()
    send_single_id = State()
    send_single_msg = State()
    broadcast_msg = State()
    add_btn_panel = State()
    add_btn_action = State()
    add_btn_row = State()
    reorder_btn = State()
    btn_move_key = State()
    graph_edit = State()
    custom_stats_start = State()
    custom_stats_end = State()
    restore_backup = State()
    antispam_interval = State()
    antispam_limit = State()
    antispam_period = State()
    antispam_duration = State()
    anon_reply_target = State()
    backup_interval = State()
    admin_anon_link = State()


class UserStates(StatesGroup):
    anon_send = State()
    file_convert = State()
    image_to_pdf = State()
    pdf_to_image = State()
    qr_input = State()
    pass_length = State()
